# Generated by Django 4.2.7 on 2025-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
